version: ~> 1.0
language: python
os: linux
dist: xenial

# If you need X11:
services:
    - xvfb

addons:
    apt:
      packages:
        - herbstluftwm
        - libxkbcommon-x11-0

env:
  global:
    - secure: "<docs build key>"

matrix:
  include:
    - name: flake8 linting
      python: 3.6
      env: LINT_PYTHON=testproject1234
    - python: 3.7

install:
  - git clone --depth 1 git://github.com/pcdshub/pcds-ci-helpers.git
  - source pcds-ci-helpers/travis/init.sh

before_script:
  # Run the window manager
  - "herbstluftwm &"
  - sleep 1

script:
  - sleep 1

import:
  - hhslepicka/pcds-ci-helpers:travis/pypi-upload.yml@pypi