import:
  - hhslepicka/pcds-ci-helpers:travis/shared_configs/python-tester-conda.yml@adjustments

jobs:
  include:
    - <<: *lcls_test_python
          name: "Python 3.6 Benchmark"
          env:
            - BENCHMARK: 1
