{% set name = "testproject1234" %}
{% set version = "0.7.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: dcb4bc27d8718d38956281f5e9605b432f8cce5881d81cb3d4409befe2848d65

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - testproject1234

about:
  home: "https://github.com/hhslepicka/testproject1234"
  license: BSD
  license_family: BSD
  license_file:
  summary: "Test Project"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - your-github-id-here
