{% set data = load_setup_py_data() %}

package:
  name: testproject1234
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  requires:
    - codecov
    - pytest
  imports:
    - testproject1234

about:
  home: "https://github.com/hhslepicka/testproject1234"
  license: BSD
  summary: "Test Project"

extra:
  recipe-maintainers:
    - ZryletTC
    - hhslepicka
